import type { NotificationType } from './notificationPolicy'
export const notificationText = {
  ru: {
    resumeTitle: 'Новое уведомление', resumeOpen: 'Открыть уведомления',
    center: 'Уведомления', settings: 'Настройки уведомлений', empty: 'Новых уведомлений пока нет', read: 'Прочитано', markRead: 'Отметить прочитанным', markAll: 'Прочитать все', close: 'Закрыть', more: 'Показать ещё', loading: 'Загрузка…', error: 'Не удалось выполнить действие. Попробуйте ещё раз.',
    inApp: 'В CRM', push: 'Push', event: 'Событие', scope: 'Чьи события получать', mine: 'Только мои', team: 'Вся команда', privacy: 'Показывать имя клиента в push-уведомлениях', privacyHelp: 'По умолчанию имя скрыто на экране блокировки.', enable: 'Включить уведомления', enabled: 'Push-уведомления включены', disable: 'Отключить на этом устройстве', masterOff: 'Отключить push на всех устройствах', permission: 'Разрешение браузера', device: 'Это устройство', devices: 'Активные устройства', active: 'Подключено', inactive: 'Не подключено', denied: 'Разрешите уведомления в настройках устройства или браузера, затем вернитесь сюда.', unsupported: 'Push недоступен в этом браузере. На iPhone добавьте LegalHub на экран «Домой» и откройте оттуда.', unavailable: 'Push ещё не включён для этого окружения.', save: 'Сохранить', saved: 'Настройки сохранены', open: 'Откройте CRM для деталей', unavailableEntity: 'Запись недоступна', back: 'Вернуться в CRM',
    permissionStates: { default: 'Не запрошено', granted: 'Разрешено', denied: 'Запрещено', unsupported: 'Не поддерживается' },
    dates: { fingerprintsDate: 'Отпечатки пальцев', predictedDecisionDate: 'Ожидаемое решение', personalAppearDate: 'Личная явка', cardPickupDate: 'Получение карты', legalStayDeadline: 'Срок легального пребывания', workContractEndDate: 'Окончание договора', custom: 'Важная дата' },
    events: { lead_assigned: 'Новый лид назначен', task_assigned: 'Новая задача назначена', task_due: 'Скоро срок задачи', task_overdue: 'Задача просрочена', case_date: 'Приближается важная дата по делу', lead_contact: 'Пора связаться с лидом' } as Record<NotificationType, string>,
  },
  uk: {
    resumeTitle: 'Нове сповіщення', resumeOpen: 'Відкрити сповіщення',
    center: 'Сповіщення', settings: 'Налаштування сповіщень', empty: 'Нових сповіщень поки немає', read: 'Прочитано', markRead: 'Позначити прочитаним', markAll: 'Прочитати всі', close: 'Закрити', more: 'Показати ще', loading: 'Завантаження…', error: 'Не вдалося виконати дію. Спробуйте ще раз.',
    inApp: 'У CRM', push: 'Push', event: 'Подія', scope: 'Чиї події отримувати', mine: 'Тільки мої', team: 'Вся команда', privacy: 'Показувати ім’я клієнта в push-сповіщеннях', privacyHelp: 'За замовчуванням ім’я приховано на екрані блокування.', enable: 'Увімкнути сповіщення', enabled: 'Push-сповіщення увімкнено', disable: 'Вимкнути на цьому пристрої', masterOff: 'Вимкнути push на всіх пристроях', permission: 'Дозвіл браузера', device: 'Цей пристрій', devices: 'Активні пристрої', active: 'Підключено', inactive: 'Не підключено', denied: 'Дозвольте сповіщення в налаштуваннях пристрою або браузера, потім поверніться сюди.', unsupported: 'Push недоступний у цьому браузері. На iPhone додайте LegalHub на екран «Додому» та відкрийте звідти.', unavailable: 'Push ще не увімкнено для цього середовища.', save: 'Зберегти', saved: 'Налаштування збережено', open: 'Відкрийте CRM для деталей', unavailableEntity: 'Запис недоступний', back: 'Повернутися до CRM',
    permissionStates: { default: 'Не запитано', granted: 'Дозволено', denied: 'Заборонено', unsupported: 'Не підтримується' },
    dates: { fingerprintsDate: 'Відбитки пальців', predictedDecisionDate: 'Очікуване рішення', personalAppearDate: 'Особиста явка', cardPickupDate: 'Отримання карти', legalStayDeadline: 'Термін легального перебування', workContractEndDate: 'Закінчення договору', custom: 'Важлива дата' },
    events: { lead_assigned: 'Новий лід призначено', task_assigned: 'Нове завдання призначено', task_due: 'Скоро термін завдання', task_overdue: 'Завдання прострочено', case_date: 'Наближається важлива дата по справі', lead_contact: 'Час зв’язатися з лідом' } as Record<NotificationType, string>,
  },
  pl: {
    resumeTitle: 'Nowe powiadomienie', resumeOpen: 'Otwórz powiadomienia',
    center: 'Powiadomienia', settings: 'Ustawienia powiadomień', empty: 'Nie ma jeszcze nowych powiadomień', read: 'Przeczytane', markRead: 'Oznacz jako przeczytane', markAll: 'Przeczytaj wszystkie', close: 'Zamknij', more: 'Pokaż więcej', loading: 'Ładowanie…', error: 'Nie udało się wykonać działania. Spróbuj ponownie.',
    inApp: 'W CRM', push: 'Push', event: 'Zdarzenie', scope: 'Czyje zdarzenia otrzymywać', mine: 'Tylko moje', team: 'Cały zespół', privacy: 'Pokaż imię klienta w powiadomieniach push', privacyHelp: 'Domyślnie imię jest ukryte na ekranie blokady.', enable: 'Włącz powiadomienia', enabled: 'Powiadomienia push włączone', disable: 'Wyłącz na tym urządzeniu', masterOff: 'Wyłącz push na wszystkich urządzeniach', permission: 'Zgoda przeglądarki', device: 'To urządzenie', devices: 'Aktywne urządzenia', active: 'Połączono', inactive: 'Nie połączono', denied: 'Zezwól na powiadomienia w ustawieniach urządzenia lub przeglądarki, a następnie wróć tutaj.', unsupported: 'Push jest niedostępny w tej przeglądarce. Na iPhonie dodaj LegalHub do ekranu początkowego i otwórz stamtąd.', unavailable: 'Push nie jest jeszcze włączony w tym środowisku.', save: 'Zapisz', saved: 'Ustawienia zapisane', open: 'Otwórz CRM, aby zobaczyć szczegóły', unavailableEntity: 'Rekord niedostępny', back: 'Wróć do CRM',
    permissionStates: { default: 'Nie zapytano', granted: 'Dozwolone', denied: 'Zablokowane', unsupported: 'Nieobsługiwane' },
    dates: { fingerprintsDate: 'Odciski palców', predictedDecisionDate: 'Przewidywana decyzja', personalAppearDate: 'Osobiste stawiennictwo', cardPickupDate: 'Odbiór karty', legalStayDeadline: 'Termin legalnego pobytu', workContractEndDate: 'Koniec umowy', custom: 'Ważna data' },
    events: { lead_assigned: 'Przydzielono nowy lead', task_assigned: 'Przydzielono nowe zadanie', task_due: 'Zbliża się termin zadania', task_overdue: 'Zadanie po terminie', case_date: 'Zbliża się ważna data sprawy', lead_contact: 'Czas skontaktować się z leadem' } as Record<NotificationType, string>,
  },
}
