ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "previousPolandEntryDate" TIMESTAMP(3);
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "previousPolandExitDate" TIMESTAMP(3);
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "previousPolandBasis" TEXT;
